### ISSUE TITLE
Getting issues with Google Pixel 4

### ISSUE THREAD

**Issue by omegazion** [love2d/love-android#200] opened 2020-11-29 15:01 UTC
I’ve recently released my game on the play store and I’ve gotten 6 separate instances of people reporting that the game never launches specifically on Google Pixel 4. (Google Pixel 4, Google Pixel 4 XL and another one with Google pixel 4a). It works perfectly on other devices.

I don’t have a Google Pixel 4 so I can only tell you what they reported to me - “For me it's auto-closing immediately after launch. I see a black screen flash briefly before returning to the screen from which I attempted to launch the app. Is this my issue or the app? I'm using an up-to-date pixel 4a.”

Link to the app if you need it: https://play.google.com/store/apps/details?id=com.dominaxisgames.android.labyrinthoflegendaryloot&hl=en . It’s not free so if you want I can give you access as a tester. I could also send you the apk, love or source code. But considering it doesn't start up at all I don't think the issue is related to the app itself.

**Comment by nequals30** [comment] 2021-01-04 02:23
I can confirm this bug exists.

I have a Pixel 4a running Android 11, and a Pixel 1 running Android 8.1.  After compiling a brand new, unmodified, APK from a clone of this repo:
* Pixel 1 (Android 8.1):  APK installs and runs as expected
* Pixel 4a (Android 11):  APK installs, but immediately crashes (and gets minimized) when trying to run it

Launching `.love` files from the Play Store version of Love2d works in Android 11, though. I get the same behaviour when trying to package my game via this method.

Does this mean no love games currently run on Android 11?

I would be happy to help debug using my 4a, but I've never used `adb`. I'm going to to spend some time figuring that works, so I can give you the results of `adb logcat` as you requested above.

**Comment by MikuAuahDark** [comment] 2021-01-04 02:56
So looks like the regression introduced by recent changes in `master` branch. If you have time figuring out how to use `adb logcat` please send me the log while it crashes. I'd highly appreciate it.

**Comment by lucasaue** [comment] 2021-01-08 21:38
Hi, we already having the same issue.

I don't have any devices to reproduce this issue but I'm using a Pixel 4 in AWS Device Farm to reproduce that.

I'm using a custom Love engine with a lot of changes and features, but I think that this problem was not caused by our modifications. 

The main error message in logcat is:
`libEGL  : call to OpenGL ES API with no current context (logged once per thread)`

To catch the complete crash backtrace I had to run our app a lot of times. Follow the crash log below:

-------------------------------------------------------------------------------------------------------

01-07 17:06:16.261  3695  3695 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
01-07 17:06:16.266  3695  3811 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7ff45f000 in tid 3811 (SDLThread), pid 3695 (ps.cowevolution)
01-07 17:06:16.268 30445 30445 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
01-07 17:06:16.268 30445 30445 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
01-07 17:06:16.276 30445 30445 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
01-07 17:06:16.329  3863  3863 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-07 17:06:16.329  3695  3813 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x77c25f8f70)
01-07 17:06:16.329  3695  3812 F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x77c25f8f70)
01-07 17:06:16.330   889   889 I tombstoned: received crash request for pid 3811
01-07 17:06:16.331  3863  3863 I crash_dump64: performing dump of process 3695 (target tid = 3811)
01-07 17:06:16.330  1249  1303 I adbd    : jdwp connection from 3695
01-07 17:06:16.334  3695  3695 I BpBinder: onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
01-07 17:06:16.341  3863  3863 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-07 17:06:16.341  3863  3863 F DEBUG   : Build fingerprint: 'google/flame/flame:11/RP1A.200720.009/6720564:user/release-keys'
01-07 17:06:16.341  3863  3863 F DEBUG   : Revision: 'MP1.0'
01-07 17:06:16.341  3863  3863 F DEBUG   : ABI: 'arm64'
01-07 17:06:16.341  3863  3863 F DEBUG   : Timestamp: 2021-01-07 17:06:16-0800
01-07 17:06:16.341  3863  3863 F DEBUG   : pid: 3695, tid: 3811, name: SDLThread  >>> br.com.tapps.cowevolution <<<
01-07 17:06:16.341  3863  3863 F DEBUG   : uid: 16152
01-07 17:06:16.341  3863  3863 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7ff45f000
01-07 17:06:16.341  3863  3863 F DEBUG   :     x0  00000074829e38c8  x1  00000074829e3cc8  x2  00000074829e30c8  x3  00000074829e40c0
01-07 17:06:16.341  3863  3863 F DEBUG   :     x4  00000074829e4cc0  x5  00000074829e44c0  x6  00000074829e48c0  x7  00000007ff45f000
01-07 17:06:16.341  3863  3863 F DEBUG   :     x8  0000000000000005  x9  0000000000020000  x10 0000000000000000  x11 00000074829e30e0
01-07 17:06:16.341  3863  3863 F DEBUG   :     x12 0000000000000a00  x13 0000000000000050  x14 0000000000000280  x15 0000000000000140
01-07 17:06:16.341  3863  3863 F DEBUG   :     x16 00000000000000a0  x17 00000074829e34c8  x18 00000000000000aa  x19 0000000000000088
01-07 17:06:16.341  3863  3863 F DEBUG   :     x20 0000000000000000  x21 0000000000000000  x22 00000075fe1cac50  x23 0000000000000100
01-07 17:06:16.341  3863  3863 F DEBUG   :     x24 0000000000000400  x25 0000000000000400  x26 00000007ff43e000  x27 0000000000000020
01-07 17:06:16.341  3863  3863 F DEBUG   :     x28 0000000000000800  x29 00000074ab2f42e0
01-07 17:06:16.341  3863  3863 F DEBUG   :     lr  0000007511b359a0  sp  00000074ab2f42b0  pc  0000007511b35ab8  pst 0000000080001000
01-07 17:06:16.360  3863  3863 F DEBUG   : backtrace:
01-07 17:06:16.360  3863  3863 F DEBUG   :       #00 pc 00000000002a3ab8  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!6b87e1463550f1ba16f38b300fd186!f84f8da!+496) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #01 pc 000000000029e29c  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!6fd1d11959478379873bee344e3720!f84f8da!+7036) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #02 pc 000000000026d160  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!e9a0267a4c3f12c4fb16e257d3a26e!f84f8da!+6192) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #03 pc 000000000027187c  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!9c0715a0352375a9ec27cf88ce6933!f84f8da!+468) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #04 pc 0000000000236898  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!e94336f9c3a8e90238c7c8557996da!f84f8da!+2776) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #05 pc 0000000000189910  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!0e6b00ab8c4b112f9f6effa6a8b2b5!f84f8da!+3720) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #06 pc 0000000000186504  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!4ecf3032464df959aad423cba1a73c!f84f8da!+1364) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #07 pc 00000000001a5164  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!141e50cb152287019aff218176d094!f84f8da!+268) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #08 pc 00000000001be678  /vendor/lib64/egl/libGLESv2_adreno.so (!!!0000!838e96e6042a39f699090106d8c25f!f84f8da!+208) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #09 pc 00000000000c95a0  /vendor/lib64/egl/libGLESv2_adreno.so (glTexSubImage2D+144) (BuildId: fec7c747f02217c94a04a68c1b19ba72)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #10 pc 000000000031be60  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #11 pc 000000000031b660  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #12 pc 000000000029b3b0  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #13 pc 000000000025cb6c  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #14 pc 000000000025c73c  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #15 pc 000000000025c078  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #16 pc 000000000027aacc  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #17 pc 000000000065f0fc  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #18 pc 00000000006607d4  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #19 pc 0000000000385670  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #20 pc 000000000003ed4c  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/libjnlua5.1.so (BuildId: 996a790618708d44fe366173b43bd0ac2df1a35d)
01-07 17:06:16.360  3863  3863 F DEBUG   :       #21 pc 000000000091118c  /data/app/~~tUYuJQjUe-Vj-NzN4hTqEw==/br.com.tapps.cowevolution-PQWhK7C9EgXiuJLHw6Htxw==/lib/arm64/liblove.so (lua_pcall+152) (BuildId: 73c190a860a484a7eb1e46ed04f5740b5037ccec)

----------------------------------------------------------------------------------------------------------

I already use the address2line to get the stack trace but the main problem cause isn't the function that reports error, but the fact is that the openGL cannot be called without a context. In some crash logs I got the error in `std::exception` function, in another I got the error in other functions. So it depends when the openGL try to draw the first object.

I know that this error occurs in some Pixel 4 and some Galaxy s20 devices, with Android 11, but there are some another Android 11 and even some another Pixel 4 (with Android 11 too) that this error doesn't occurs. 

I received a report from OPPO (chinese devices factory) that this error are occurring with the last Android 11 kernel build, so in Pixel 3 (Android11, kernel 4.9.223) this error doesn't occurs but with Pixel 4 (Android11, kernel 4.14.19) this error are occurring.

--------- beginning OPPO report -------

Issue information:
Device, Model, Android ,OS: OPPO Reno 4 Pro，Android 11.0，OS 11（Google pixel4（Android11）,Mi 10（Android11）,OPPO findx2 （Android11）have the same issue）
Reproduce Frequency :10/10
Estimated impact:
All Android11 users are affected
Reproduce steps:
【Preconditions】Download the latest version of APP from the Google Store
【Operation Steps】1: Click on the APP on the desktop
2: Observe the phenomenon
Actual result：APP crashes and cannot be used normally
Expected result: Can enter and use normally
Analysis from our engineers:1. The application uses an illegal display and a destroyed lock
2. Incompatible with the new kernel
2.Android10 device is normal

--------- ending OPPO report -------

I already tested update NDK and remove a lot of app features (ex: Firebase, GoogleStoreAPI, ...) but with no positive results.

If you need more informations, I can send a e-mail with my completed logcat files from our tests and from OPPO test too. I'll continue investigating this issue and I hope return with a solution soon.

**Comment by MikuAuahDark** [comment] 2021-01-09 03:37
`01-07 17:06:16.261 3695 3695 E libEGL : call to OpenGL ES API with no current context (logged once per thread)` is most of the time harmless (I've seen it both in my Mi A1 and Redmi Note 9). I'd suggest updating to 11.3 since that contains some fixes related to Adreno GPUs. And if you can try love2d/love#1662 (which will be merged later, needs more testing), I'd appreciate it.

**Comment by MikuAuahDark** [comment] 2021-01-09 16:51
To OP, can you test if the recent APKs generated by the GitHub Actions artifacts fixes the issue? You can get it here: https://github.com/love2d/love-android/actions/runs/474243323

**Comment by lucasaue** [comment] 2021-01-11 14:11
Hi, I've tested the last debug apk with Pixel 4 and the crash still occurs. 

The logcat file: https://drive.google.com/file/d/1wMzTFwVTR7ueskav6E6ZmdJ2D7qLQ2Pm/view?usp=sharing
The Fuzz test video file: https://drive.google.com/file/d/1Nb2kbWeuXha_AuTO1tt8lFogJP2Vr8eP/view?usp=sharing

If you need more informations, just tell me.

**Comment by MikuAuahDark** [comment] 2021-01-11 14:37
Checking the logcat looks like there's no problem as I don't see any crash logs related to the app. The log is kinda large so I only did "search" the relevant lines. Protip: Run `adb logcat -c` before launching the app, then `adb logcat` then launch the app.

I checked the video and the balloon image shows up for a second then black screen. That means the no-game screen bootup properly at least. However it then followed by black screen. There's known issue about black screen for "normal" APK builds if you exit the game then open it again, but fixing this black screen issue requires refactoring the Android-specific code and upstream code.

That's being said, it normally doesn't happen when someone finally "fuse" their game inside the APK.

**Comment by lucasaue** [comment] 2021-01-13 15:31
I did more tests and I founded that the Pixel 4 (Android 11) works fine if I build the Android project without arm64-v8a architecture. Now I will find the arm64-v8a arch problem.

I think that the normal Love apk go to the black screen before the crash. With some logs in my app, I founded that the app crashs after render 10/15 frames, but as I said, I'm using the AWS device farm to automatically run my tests, so I can't interact with the device and I can't confirm if the Love apk crashs or not.

**Comment by MikuAuahDark** [comment] 2021-01-13 15:44
ARM64 arch is required to comply with Play Store requirements so that can't be removed. Anyway could you try the latest "master" artifacts? I reapply some patches which may workaround the black screen problem.

**Comment by lucasaue** [comment] 2021-01-14 01:55
I tested the build 27 and I got the same results. The funny thing is that the black screen problem only occurs in Pixel 4 device. I uploaded the video and the logcat from the Pixel 3a XL (Android 11) and the Pixel 4 (Android 11) to you see the diff. Both devices uses ARMv8+ architecture but as in my apps, the Pixel 3a XL works fine but the Pixel 4 doesn't work.

Pixel 3a XL - Android 11
Video: https://drive.google.com/file/d/1C2ermsrlUGGMU0JYo2bh_Eug6ONCFcaR/view?usp=sharing
Logcat: https://drive.google.com/file/d/1YMgrdf3gDtK6hVZReSn_kTrHWv3GnkhU/view?usp=sharing

Pixel 4 - Android 11
Video: https://drive.google.com/file/d/1R5Hfa4CBAmHLjgGeBEmPuBvCZuHe_q9J/view?usp=sharing
Logcat: https://drive.google.com/file/d/1rIs-P-4pH19zbLE-qALSHCqwH3hxqGjz/view?usp=sharing

I already tested rebuild LuaJIT with the new NDK version and escape Tagged Pointers (https://source.android.com/devices/tech/debug/tagged-pointers) but without any positive results.

**Comment by lucasaue** [comment] 2021-01-14 02:21
I founded the same issue in Unity too, in this forum: https://forum.unity.com/threads/android-11-il2cpp-arm64-crash-in-unity-lts-2019-4-12f1.986883/

The Unity maintainer said:

**User:** 
_I'm however also curious if you've stopped exploring the HWAsan on Android 11 crash. I understand that it won't be supported to create an HWAsan build of Unity until NDK 21+ hits Unity main (2021.1) but it still feels suspicious that an empty project would crash only on Arm64 + IL2CPP on HWAsan but not on Armv7 + IL2CPP or mono. Did that investigation uncover any hints on where the root cause might lie?_

**Maintainer:** 
_There is a reason, HWAsan uses higher pointer bits for its purposes, and that confused internal memory allocator in Unity, since it also uses some of the high bits for book keeping purposes. Long story short, Unity's internal memory allocator mistakenly started to assume that more than 16 GB of memory is being used while in reality those were simply tags used by HWAsan._

_Nevertheless, it seems due allocator changes in Android 11 to Scudo, even without using HWAsan, the 16GB error occurs. Our QA currently trying to reproduce this on factory Android builds, once this done, we'll be sure that our fix will apply both for factory and aosp builds._

_Our preliminary fix most likely be to switch to a different internal Unity allocator which doesn't use high bits, but it also uses a different way of allocating memory, by using blocks. That also means that HWAsan might not be able to correctly show the origin of allocation at least for internal Unity allocations, it will still continue to work fine for external allocations though._

**Comment by MikuAuahDark** [comment] 2021-01-14 06:24
HWAsan is something I just know. That explains why previously LOVE bail out because it sees the high pointer is being set. However, this HWAsan-related problem should be fixed in love2d/love@4f491c2e6162ff880818b4725a0c59912ca2c6c7.

In your Pixel 4 logcat, I can't find any `org.love2d.android` strings. Also I saw OpenAL-soft 1.18.1, which is not what the latest `master` branch uses (FYI: `master` uses 1.20.1). Are you really sure you're putting the LOVE APK correctly like what you did in Pixel 3?

**Comment by lucasaue** [comment] 2021-01-15 14:56
Sorry, my mistake. I uploaded the right video but the wrong logcat. The test run in the 2 devices simultaneously.

This is the real logcat file: https://drive.google.com/file/d/1G2AEfx189i1D6KZ_4gJ6MbJcnYoQTlwO/view?usp=sharing

**Comment by MikuAuahDark** [comment] 2021-01-15 15:38
Looks like it's not really crashing, but it receives endless amount of `onNewIntent()` event.

```
01-13 17:13:16.959 22203 22203 D GameActivity: onNewIntent() with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.love2d.android/.GameActivity }
```

That event is treated as LOVE to forcefully kill the program then start it back, thus you keep seeing black screen because the game never really runs(?) . On the other hand, I also saw lots of `onPause()`, `onResume()`, and `onWindowFocusChanged()` events, which means somehow it keeps gaining and losing focus. Furthermore, I never see any calls to `nativeRunMain()`.

Is it because the input tester keep pulling the status bar every single time? I'm not sure what's going on at that device farm. Someone is probably needs to test this in **real device** without any input tester or something like that.

**Comment by saintlyvermin** [comment] 2021-01-15 22:30
Facing same issue on Galaxy S20 5G and S20 FE (both Android 11). Installs fine but crashes. I was wondering if it is related to storage permission because Android 11 has changed storage permissions i guess. But I am not sure. Desperately need help. Please fix this.

**Comment by slime73** [comment] 2021-01-15 22:38
> Facing same issue on Galaxy S20 5G and S20 FE (both Android 11)

Did you try AuahDark's suggestion of using updated APKs he linked? If yes and the crash still happens, can you provide more info such as logcat files? Depending on the specifics of your crashes it might (or might not) be suited for a separate issue report.

**Comment by saintlyvermin** [comment] 2021-01-15 22:52
> > Facing same issue on Galaxy S20 5G and S20 FE (both Android 11)
> 
> Did you try AuahDark's suggestion of using updated APKs he linked? If yes and the crash still happens, can you provide more info such as logcat files? Depending on the specifics of your crashes it might (or might not) be better suited for a separate issue report.

I can see many apks in the link that AuahDark shared... but i am not sure how to make my apk work in Android using the apks that he shared. Could you please explain the process a bit? That would be great. Thanks.

**Comment by MikuAuahDark** [comment] 2021-01-16 02:39
Sideload [`love-android-debug.apk`](https://github.com/love2d/love-android/actions/runs/484731665) (uninstall existing LOVE for Android first) using `adb install -t` then test again.

**Comment by lp-pinheiro** [comment] 2021-02-25 20:18
Are there any updates on this issue? Our games run on an engine built on top of Love2D and we are having the same problem.

**Comment by slime73** [comment] 2021-02-25 20:35
> Are there any updates on this issue?

Yes: https://github.com/love2d/love-android/issues/200#issuecomment-759533494

Do you still have issues after using the latest code or APKs?

**Comment by saintlyvermin** [comment] 2021-02-25 20:46
> 
> 
> > Are there any updates on this issue?
> 
> Yes: [#200 (comment)](https://github.com/love2d/love-android/issues/200#issuecomment-759533494)
> 
> Do you still have issues after using the latest code or APKs?

Apk works

**Comment by lp-pinheiro** [comment] 2021-02-25 21:43
Can someone point me to which code change actually solved the problem?
Our engine is actually a heavily modified version of the original Love2D, so I will probably have to duplicate the change on my side.

**Comment by MikuAuahDark** [comment] 2021-02-26 00:30
You need to update LuaJIT to at least LuaJIT/LuaJIT@e9af1ab then apply love2d/love@4f491c2.

Since latest APK is proven to works, I'll close this issue now.

**Closed by MikuAuahDark** 2021-02-26 00:30 UTC
Labels: bug

**Comment by himelsaha29** [comment] 2021-02-26 21:05
> 
> 
> Can someone point me to which code change actually solved the problem?
> Our engine is actually a heavily modified version of the original Love2D, so I will probably have to duplicate the change on my side.

I have built the APK using the updated repository and it solved issues like Android 11 launch crash and black screen issue. Changes made to the repository on January 21st worked perfectly for me.
