### ISSUE TITLE
Remove "Hacky" SDL force restart and expose some love.event functions to Java side.

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d/love-android#189] opened 2020-02-27 03:12 UTC
Currently there's "hacky" code which forcefully kills the native instance of SDL to restart the game (#36). I think we shouldn't depend on these kind of things and think something else. This also cause other issue like [this](https://love2d.org/forums/viewtopic.php?f=4&t=87821).

I was thinking of exposing `love.event.push` and `love.event.quit` function to the Java side so we can simply send `love.event.quit("restart")` when new LOVE file received, but this also mean quitting depends on the game behavior. What if the game prevent exit?

https://github.com/love2d/love-android/blob/ea8648acfb0bc07b4397232caec101f614d74d8a/love/src/main/java/org/love2d/android/GameActivity.java#L126-L134

Note that lines above are supressed when running "embed" variant of the APK.

https://github.com/love2d/love-android/blob/ea8648acfb0bc07b4397232caec101f614d74d8a/love/src/jni/SDL2/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L74

https://github.com/love2d/love-android/blob/ea8648acfb0bc07b4397232caec101f614d74d8a/love/src/jni/SDL2/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L180

https://github.com/love2d/love-android/blob/ea8648acfb0bc07b4397232caec101f614d74d8a/love/src/jni/SDL2/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L239-L287

https://github.com/love2d/love-android/blob/ea8648acfb0bc07b4397232caec101f614d74d8a/love/src/jni/SDL2/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L435-L462

**Comment by jmiskovic** [comment] 2020-04-11 06:08
Last release of my released app was based on 11.1 and didn't have issues restarting. Now I'm rebasing to 11.3 and there is black screen when starting app for second time. I'd like to get this issue fixed, as I don't want to make a new release with such regression.

@MikuAuahDark those snippets you included in text are already merged in codebase, except for the first one. If SDL instance is forcefully killed, then it should restart cleanly, right?

**Comment by MikuAuahDark** [comment] 2020-04-11 06:28
Forcefully killed can mean two things: Forcefully closed from the recent app list or when tapping the game icon when not using embed variant. The former is completely fine, but the latter sort of undefined behavior.

> those snippets you included in text are already merged in codebase

Yes, those snippets I provided exist in LOVE Android modified SDL, and those snippets are hacky, hence the issue. If you could try to build the embed APK (with `gradle assembleEmbedRelease`) and use that APK, can you still reproduce the black screen problem?

**Comment by jmiskovic** [comment] 2020-04-11 08:36
Normally I build the signed release version in android studio from source and insert my `game.love` in assets. I tried but I could not build my own embed APK release, sorry.

Instead I tried official releases from this repo. When I embed my `game.love` into `love-11.3-android-embed.apk`, I can "re-launch" the application normally. The app is just resumed and there is no black screen issue.

When I try official release `love-11.3-android.apk` without any loaded assets (the balloon 'game'), I get black screen issue when re-running the app. Maybe we can focus on this issue because it is easily reproducible and already present in official release?

**Comment by MikuAuahDark** [comment] 2020-04-11 11:15
Both APK serves different purpose, as of 11.3:

* `love-11.3-android.apk` allows you to run LOVE apps directly by placing it in `/sdcard/lovegame` by downloading it, or if you're lucky, via file manager. I can't get the latter work across all platforms due to Android 7 and later restrictions.

* `love-11.3-android-embed.apk` lacks that functionality and exactly meant for embedding purpose, hence the name, You put your game.love inside the APK then just deploy, without worrying about stuff present in `love-11.3-android.apk`.

The way to fix this black screen is by actually fixing this issue.

**Comment by jmiskovic** [comment] 2020-04-11 11:44
The `love-11.3-android.apk` works for perfectly for me on Android 10. I have to grant the app permissions to access external storage, and files that go inside `/sdcard/lovegame` have to be unpacked (as per `GameActivity.java`).

I noticed that I rebased to tag 11.3a instead of origin/master. I'll try to custom build the latest source with my assets included internally, to see how it behaves.

**Comment by MikuAuahDark** [comment] 2020-04-11 11:48
Ah yeah, make sure to use the `master` branch as separation between normal, play store, and embed builds are in `master` banch.

`development` branch uses LOVE `12.0-development` branch so that shouldn't be used.

**Closed** 2022-05-23 01:28 UTC
Labels: change
